name: Build_Deploy
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "Get Code"
        uses: actions/checkout@v4
      - name: "Install npm & dependecies"
        run: |
          npm install
          npm ci
      - name: "Build app"
        run: npm run build
      - name: "Check"
        run: ls
