name: Build_Deploy
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "Get Code"
        uses: actions/checkout@v4
      - name: "Spin up node image"
        run: docker run --name=node --mount type=bind,src=${{ github.workspace }},dst=/var/www -d node sleep 1000
      - name: "Install dependencies"
        run: docker exec node npm ci
      - name: "Build app"
        run: docker exec node npm run build --prefix /var/www
      - run: ls
