name: "ED"
on: [issues, workflow_dispatch]
jobs:
  Output_Details:
    runs-on: ubuntu-slim
    steps:
      - name: "Install JQ"
        run: sudo apt install jq
      - name: "Get event details"
        run: echo "${{ github }}" | jq
