name: "1st"
on: push
jobs:
  Lint:
    runs-on: ubuntu-slim
    steps:
      - name: "Get Code"
        uses: action/checkout@v3
      - name: "Install Dependencies"
        run: npm ci
      - name: "Run lint"
        run: npm lint
  Test:
    runs-on: ubuntu-slim
    steps:
      - name: "Get Code"
        uses: action/checkout@v3
      - name: "Install Dependencies"
        run: npm ci
      - name: "Run test"
        run: npm test
  Deploy:
    runs-on: ubuntu-slim
    steps:
      - name: "Get Code"
        uses: action/checkout@v3
      - name: "Install Dependencies"
        run: npm ci
      - name: "Lint"
        run: npm run build
